use GARA

insert into WAGE values
    (N'Rửa xe', 1),
    (N'Sửa chữa',1),
    (N'Vận chuyển',1),
    (N'Dán decal nguyên xe 4 chỗ',1),
    (N'Dán decal nguyên xe 7 chỗ',1),
    (N'Dán decal mui đen bóng 3M',1),
    (N'Dán phim PPF - Thailand 4 chỗ',1),
    (N'Dán phim PPF - Thailand 7 chỗ',1),
    (N'Dán phim PPF - Hexis Pháp 4 chỗ',1),
    (N'Dán phim PPF - Hexis Pháp 7 chỗ',1),
    (N'Dán kính chống mưa chiếu hậu',1),
    (N'Dán phim cách nhiệt 3M xe 4 chỗ',1),
    (N'Dán phim cách nhiệt 3M xe 7 chỗ',1),
    (N'Sơn phủ gầm',1),
    (N'Sơn lót chống gỉ',1),
    (N'Sơn mâm',1),
    (N'Sơn mâm kĩ thuật',1),
    (N'Sơn mâm chrome',1),
    (N'Sơn mui',1),
    (N'Sơn demi 4 chỗ',1),
    (N'Sơn demi 7 chỗ',1),
    (N'Sơn đổi màu 4D',1),
    (N'Sơn phủ carbon',1),
    (N'Sơn phủ gốm/Ceramic',1),
    (N'Sơn nano',1),
    (N'Sơn cùm thắng',1),
    (N'Sơn tút chi tiết',1),
    (N'Độ vòng Angel Eyes',1),
    (N'Mài matit',1),
    (N'Bơm nitro bảo vệ vỏ',1),
    (N'Vệ sinh họng ga',1),
    (N'Vệ sinh kim phun',1),
    (N'Vệ sinh bugi',1),
    (N'Vệ sinh, thay dầu thắng',1),
    (N'Vệ sinh, thay dầu trợ lực lái',1),
    (N'Vệ sinh lọc gió',1),
    (N'Vệ sinh khoang máy (Nhỏ)',1),
    (N'Vệ sinh khoang máy SUV, Sedan C',1),
    (N'Vệ sinh khoang máy xe EC, SUV',1),
    (N'Vệ sinh gầm',1),
    (N'Vệ sinh hộp, cảm biến trên khoang máy',1),
    (N'Vệ sinh bình xăng con',1),
    (N'Vệ sinh, bảo dưỡng nội thất 4 chỗ',1),
    (N'Vệ sinh, bảo dưỡng nội thất 7 chỗ',1),
    (N'Vệ sinh, tiệt trùng nội thất',1),
    (N'Vệ sinh dàn lạnh(1) & dàn nóng',1),
    (N'Vệ sinh dàn lạnh(2) & dàn nóng',1),
    (N'Sạc Gas & vệ sinh dàn nóng(1 dàn lạnh)',1),
    (N'Sạc Gas & vệ sinh dàn nóng(2 dàn lạnh)',1),
    (N'Tẩy sét, mạ kẽm ống xả',1),
    (N'Đánh Pát xe 4 chỗ',1),
    (N'Đánh Pát xe 7 chỗ',1),
    (N'Làm mới dàn nhựa ốp',1),
    (N'Đánh bóng kính, tẩy ố kính',1),
    (N'Hàn kính ô tô',1),
    (N'Căn chỉnh xupap',1),
    (N'Bảo dưỡng quạt tản nhiệt',1),
    (N'Bảo dưỡng ACCU',1),
    (N'Bảo dưỡng Dynamo',1),
    (N'Bảo dưỡng bộ khởi động',1),
    (N'Bảo dưỡng lọc xăng',1),
    (N'Bảo dưỡng hệ thống lái',1),
    (N'Bảo dưỡng bơm trợ lực lái',1),
    (N'Bảo dưỡng chân ga, ly hợp và phanh tay',1),
    (N'Bảo dưỡng hệ thống điện lạnh',1),
    (N'Thay nhớt máy',1),
    (N'Thay nhớt cầu',1),
    (N'Thay nhớt hộp số dưới 6 cấp',1),
    (N'Thay nhớt hộp số',1),
    (N'Thay nước làm mát',1),
    (N'Thay nước nước rửa kính',1),
    (N'Thay hộp số',1),
    (N'Thay ghế ngồi',1),
    (N'Thay dây an toàn',1),
    (N'Thay kính trời Panorama',1),
    (N'Thay lót sàn 5D 4 chỗ, Gros/Full cốp',1),
    (N'Thay lót sàn 5D 7 chỗ, Gross/Full cốp',1),
    (N'Bọc Plastic Lafon trần 4 chỗ',1),
    (N'Bọc Plastic Lafon tràn 7 chỗ',1),
    (N'Thay lắp đèn xenon',1),
    (N'Thay lắp đèn LED gầm',1),
    (N'Thay lắp LED gương hậu',1),
    (N'Thay lắp ắc quy', 1),
    (N'Thay lắp bọc vô lăng',1),
    (N'Thay lắp trục dẫn động',1),
    (N'Thay lắp khoang chứa đồ',1),
    (N'Thay lắp bộ chữa cháy',1),
    (N'Thay lắp hệ thống búa phá kính, đèn pin khẩn cấp',1),
    (N'Thay lắp vô lăng', 1),
    (N'Thay lắp bình xăng', 1),
    (N'Thay lắp bơm xăng',1),
    (N'Thay lắp lọc xăng',1),
    (N'Thay lắp lọc nhiên liệu',1),
    (N'Thay lắp cảm biến báo xăng',1),
    (N'Thay lắp bơm cao áp', 1),
    (N'Thay lắp két làm mát',1),
    (N'Thay lắp quạt gió động cơ',1),
    (N'Thay lắp xupap hút', 1),
    (N'Thay lắp xupap xả',1),
    (N'Thay lắp piston', 1),
    (N'Thay lắp trục cơ', 1),
    (N'Thay lắp segment', 1),
    (N'Thay lắp máy đề', 1),
    (N'Thay lắp bơm dầu', 1),
    (N'Thay lắp bugi',1),
    (N'Thay lắp má phanh', 1),
    (N'Thay đĩa phanh', 1),
    (N'Thay lắp gương chiếu hậu',1),
    (N'Thay lắp đèn pha', 1),
    (N'Thay lắp lọc gió điều hòa',1),
    (N'Thay lắp cụm ABS', 1),
    (N'Thay lắp lốp vỏ xe', 1),
    (N'Thay lắp kính chắn gió',1),
    (N'Thay lắp ống xả',1),
    (N'Thay lắp gập gương tự động',1),
    (N'Thay lắp Pallast(Phillips/Denso)',1),
    (N'Thay lắp gạt mưa',1),
    (N'Thay lắp lock cửa remote',1),
    (N'Thay lắp hệ thống lên kính tự động',1),
    (N'Thay lắp camera lùi',1),
    (N'Thay lắp camera hông',1),
    (N'Thay lắp camera tơi',1),
    (N'Thay lắp camera hành trình',1),
    (N'Thay lắp camera 360',1),
    (N'Thay lắp TPMS/Cảm biến áp suất lốp',1),
    (N'Thay lắp hệ thống cảm biến HUD/Hiển thị thông số vận hành',1),
    (N'Thay lắp amply điện Pioneer',1),
    (N'Thay lắp hệ thống cách âm',1),
    (N'Thay lắp hệ thống GPS, kiểm soát hành trình',1),
    (N'Thay lắp hệ thống mở cốp xe tự động',1),
    (N'Thay lắp hệ thống start-stop smart key',1),
    (N'Thay lắp loa cửa Pioneer/JBL',1),
    (N'Thay lắp đầu Android',1),
    (N'Thay lắp đầu DVD ghế sau',1),
    (N'Thay lắp đầu DVD ốp trần',1),
    (N'Thay lắp gương trung tâm tích hợp DVD',1),
    (N'Thay lắp kèn Bosch/Denso',1),
    (N'Thay biển số mica/inox',1),
    (N'Thay biển số mica/inox có cờ',1),
    (N'Bảo hiểm vật chất',1),
    (N'Bảo hiểm dân sự 4 chỗ',1),
    (N'Bảo hiểm dân sự 7 chỗ',1),
    (N'Bảo hiểm dân sự 7 chỗ kinh doanh',1),
    (N'Bảo hiểm dân sự 16 chỗ',1),
    (N'Bảo hiểm dân sự 16 chỗ kinh doanh',1),
    (N'Phí cầu đường bộ',1),
    (N'Đăng kiểm',1),
    (N'Trước bạ sang tên',1),
    (N'Đổi chủ quyền cavet',1),
    (N'Đổi biển số vuông qua biển số dài',1)