//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_IN_DEBT : BaseViewModel
    {
        private int _License_ID;
        public int License_ID
        {
            get => _License_ID;
            set { _License_ID = value; OnPropertyChanged(); }
        }

        private Nullable<int> _Debt;
        public Nullable<int> Debt
        {
            get => _Debt;
            set { _Debt = value; OnPropertyChanged(); }
        }

        private LICENSE_PLATE _LICENSE_PLATE;
        public virtual LICENSE_PLATE LICENSE_PLATE
        {
            get => _LICENSE_PLATE;
            set { _LICENSE_PLATE = value; OnPropertyChanged(); }
        }
    }
}
