//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
  
    public partial class CAR_BRAND : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR_BRAND()
        {
            this.LICENSE_PLATE = new HashSet<LICENSE_PLATE>();
            this.RECEIVING_TICKET = new HashSet<RECEIVING_TICKET>();
        }

        private int _ID;
        public int ID
        {
            get => _ID;
            set { _ID = value; OnPropertyChanged(); }
        }

        private string _Name;
        public string Name
        {
            get => _Name;
            set { _Name = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<LICENSE_PLATE> _LICENSE_PLATE;
        public virtual ICollection<LICENSE_PLATE> LICENSE_PLATE
        {
            get => _LICENSE_PLATE;
            set { _LICENSE_PLATE = value; OnPropertyChanged(); }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<RECEIVING_TICKET> _RECEIVING_TICKET;
        public virtual ICollection<RECEIVING_TICKET> RECEIVING_TICKET
        {
            get => _RECEIVING_TICKET;
            set { _RECEIVING_TICKET = value; OnPropertyChanged(); }
        }
    }
}
