//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRECEPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRECEPTION()
        {
            this.RECEIPTs = new HashSet<RECEIPT>();
            this.REPAIRFORMs = new HashSet<REPAIRFORM>();
        }
    
        public int Id { get; set; }
        public int IdCustomer { get; set; }
        public string LicensePlate { get; set; }
        public int IdBrand { get; set; }
        public System.DateTime? ReceptionDate { get; set; }
        public int IdStatus { get; set; }
    
        public virtual CARBRAND CARBRAND { get; set; }
        public virtual CARSTATUS CARSTATUS { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRFORM> REPAIRFORMs { get; set; }
    }
}
