//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CarReception :BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarReception()
        {
            this.Receipts = new HashSet<Receipt>();
            this.RepairForms = new HashSet<RepairForm>();
        }

        private int _Id { get; set; }
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private int _IdCustomer { get; set; }
        public int IdCustomer { get => _IdCustomer; set { _IdCustomer = value; OnPropertyChanged(); } }
        private string _LicensePlate { get; set; }
        public string LicensePlate { get => _LicensePlate; set { _LicensePlate = value; OnPropertyChanged(); } }
        private int _IdBrand { get; set; }
        public int IdBrand { get => _IdBrand; set { _IdBrand = value; OnPropertyChanged(); } }
        private System.DateTime? _ReceptionDate { get; set; }
        public System.DateTime? ReceptionDate { get => _ReceptionDate; set { _ReceptionDate = value; OnPropertyChanged(); } }
        private int _IdStatus { get; set; }
        public int IdStatus { get => _IdStatus; set { _IdStatus = value; OnPropertyChanged(); } }
        private CarBrand _CarBrand { get; set; }
        public virtual CarBrand CarBrand { get => _CarBrand; set { _CarBrand = value; OnPropertyChanged(); } }
        private CarStatus _CarStatus { get; set; }
        public virtual CarStatus CarStatus { get => _CarStatus; set { _CarStatus = value; OnPropertyChanged(); } }
        private Customer _Customer { get; set; }
        public virtual Customer Customer { get => _Customer; set { _Customer = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairForm> RepairForms { get; set; }
    }
}
