//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class GaraInfo : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GaraInfo()
        {
            this.Receipts = new HashSet<Receipt>();
        }

        private int _Id;
        public int Id
        {
            get => _Id;
            set { _Id = value; OnPropertyChanged(); }
        }
        private Nullable<int> _MaxCar;
        public Nullable<int> MaxCar
        {
            get => _MaxCar;
            set { _MaxCar = value; OnPropertyChanged(); }
        }
        private Nullable<int> _MaxCarReceiption;
        public Nullable<int> MaxCarReceiption
        {
            get => _MaxCarReceiption;
            set { _MaxCarReceiption = value; OnPropertyChanged(); }
        }
        private string _Phone;
        public string Phone
        {
            get => _Phone;
            set { _Phone = value; OnPropertyChanged(); }
        }
        private string _Email;
        public string Email
        {
            get => _Email;
            set { _Email = value; OnPropertyChanged(); }
        }
        private string _Address;
        public string Address
        {
            get => _Address;
            set { _Address = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Receipt> _Receipts;
        public virtual ICollection<Receipt> Receipts
        {
            get => _Receipts;
            set { _Receipts = value; OnPropertyChanged(); }
        }
    }
}
