//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GARAEntities : DbContext
    {
        public GARAEntities()
            : base("name=GARAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR_BRAND> CAR_BRAND { get; set; }
        public virtual DbSet<CAR_IN_DEBT> CAR_IN_DEBT { get; set; }
        public virtual DbSet<CAR_STATUS> CAR_STATUS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<GARA_SERVICE> GARA_SERVICE { get; set; }
        public virtual DbSet<LICENSE_PLATE> LICENSE_PLATE { get; set; }
        public virtual DbSet<RECEIPT> RECEIPTs { get; set; }
        public virtual DbSet<RECEIVING_TICKET> RECEIVING_TICKET { get; set; }
        public virtual DbSet<REPAIR_TICKET> REPAIR_TICKET { get; set; }
        public virtual DbSet<STAFF_ACCOUNT> STAFF_ACCOUNT { get; set; }
        public virtual DbSet<STAFF_INFORMATION> STAFF_INFORMATION { get; set; }
        public virtual DbSet<SUPPLIES> SUPPLIES { get; set; }
    }
}
