//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GARAEntities : DbContext
    {
        public GARAEntities()
            : base("name=GARAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarBrand> CarBrands { get; set; }
        public virtual DbSet<CarReception> CarReceptions { get; set; }
        public virtual DbSet<CarStatus> CarStatus1 { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GaraInfo> GaraInfoes { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Recept> Recepts { get; set; }
        public virtual DbSet<RepairForm> RepairForms { get; set; }
        public virtual DbSet<RepairInfo> RepairInfoes { get; set; }
        public virtual DbSet<Supply> Supplies { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
