//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARAINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GARAINFO()
        {
            this.RECEIPTs = new HashSet<RECEIPT>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaxCar { get; set; }
        public Nullable<int> MaxCarReception { get; set; }
        public string GaraInfo_Phone { get; set; }
        public string GaraInfo_Email { get; set; }
        public string GaraInfo_Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
    }
}
