//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARA_INFO
    {
        public int GaraInfo_Id { get; set; }
        public Nullable<int> MaxCarReception { get; set; }
        public Nullable<bool> IsOverPay { get; set; }
    }
}
