//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_GOODS_DETAIL
    {
        public int IdImportGood { get; set; }
        public int IdSupplies { get; set; }
        public int Amount { get; set; }
        public int Price { get; set; }
        public int TotalMoney { get; set; }
    
        public virtual IMPORT_GOODS IMPORT_GOODS { get; set; }
        public virtual SUPPLIES SUPPLIES { get; set; }
    }
}
