//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        public int Id { get; set; }
        public int IdCarReception { get; set; }
        public int IdGaraInfo { get; set; }
        public System.DateTime ReceptDate { get; set; }
        public int TotalMoney { get; set; }
    
        public virtual CARRECEPTION CARRECEPTION { get; set; }
        public virtual GARAINFO GARAINFO { get; set; }
    }
}
