//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        public int License_ID { get; set; }
        public string Email_Address { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual LICENSE_PLATE LICENSE_PLATE { get; set; }
    }
}
