//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT : BaseViewModel
    {
        private int _License_ID;
        public int License_ID
        {
            get => _License_ID;
            set { _License_ID = value; OnPropertyChanged(); }
        }
        private string _Email_Address;
        public string Email_Address
        {
            get => _Email_Address;
            set { _Email_Address = value; OnPropertyChanged(); }
        }
        private System.DateTime _Receipt_Date;
        public System.DateTime Receipt_Date
        {
            get => _Receipt_Date;
            set { _Receipt_Date = value; OnPropertyChanged(); }
        }
        private int _Total_Money;
        public int Total_Money
        {
            get => _Total_Money;
            set { _Total_Money = value; OnPropertyChanged(); }
        }
        private bool _IsPayed;
        public bool IsPayed
        {
            get => _IsPayed;
            set { _IsPayed = value; OnPropertyChanged(); }
        }

        private LICENSE_PLATE _LICENSE_PLATE;
        public virtual LICENSE_PLATE LICENSE_PLATE
        {
            get => _LICENSE_PLATE;
            set { _LICENSE_PLATE = value; OnPropertyChanged(); }
        }
    }
}
