//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVING_TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEIVING_TICKET()
        {
            this.REPAIR_TICKET = new HashSet<REPAIR_TICKET>();
        }
    
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public int License_ID { get; set; }
        public int Brand_ID { get; set; }
        public System.DateTime Receiving_Date { get; set; }
    
        public virtual CAR_BRAND CAR_BRAND { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual LICENSE_PLATE LICENSE_PLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIR_TICKET> REPAIR_TICKET { get; set; }
    }
}
