//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_DETAIL
    {
        public int RoleDetail_Id { get; set; }
        public int IdRole { get; set; }
        public int IdPermissionItem { get; set; }
        public bool Permission { get; set; }
    
        public virtual PREMISSION_ITEM PREMISSION_ITEM { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
