//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_INFO
    {
        public int RoleInfo_Id { get; set; }
        public int IdRole { get; set; }
        public bool AccessDashBoard { get; set; }
        public bool AccessService { get; set; }
        public bool AccessEmployee { get; set; }
        public bool AccessSetting { get; set; }
        public bool AccessReport { get; set; }
        public bool AccessInventory { get; set; }
        public bool AllowAddSupplies { get; set; }
        public bool AllowAddCarBrand { get; set; }
        public bool AllowAddAccount { get; set; }
        public bool AllowAddWage { get; set; }
        public bool AllowEditGaraInfo { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
