//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_REPORT : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALES_REPORT()
        {
            this.SALES_REPORT_DETAIL = new HashSet<SALES_REPORT_DETAIL>();
        }
    
        public int SalesReport_Id { get; set; }
        public System.DateTime SalesReport_Date { get; set; }
        public int SalesReport_Revenue { get; set; }
        public string SalesReport_UserName { get; set; }
        public int IdUser { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_REPORT_DETAIL> SALES_REPORT_DETAIL { get; set; }
    }
}
