//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_INFORMATION
    {
        public int Staff_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Telephone { get; set; }
        public string CMND { get; set; }
    
        public virtual STAFF_ACCOUNT STAFF_ACCOUNT { get; set; }
    }
}
