//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using QuanLyGaraOto.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_ACCOUNT : BaseViewModel
    {
        private int _ID;
        public int ID
        {
            get => _ID;
            set { _ID = value; OnPropertyChanged(); }
        }
        private string _User_Name;
        public string User_Name
        {
            get => _User_Name;
            set { _User_Name = value; OnPropertyChanged(); }
        }
        private string _Password;
        public string Password
        {
            get => _Password;
            set { _Password = value; OnPropertyChanged(); }
        }
        private string _Role;
        public string Role
        {
            get => _Role;
            set { _Role = value; OnPropertyChanged(); }
        }

        private STAFF_INFORMATION _STAFF_INFORMATION;
        public virtual STAFF_INFORMATION STAFF_INFORMATION
        {
            get => _STAFF_INFORMATION;
            set { _STAFF_INFORMATION = value; OnPropertyChanged(); }
        }
    }
}
