//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIES
    {
        public string Supplies_ID { get; set; }
        public string Supplies_Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
