//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public int UserInfo_Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string UserInfo_Name { get; set; }
        public string UserInfo_Address { get; set; }
        public Nullable<System.DateTime> UserInfo_BirthDate { get; set; }
        public string UserInfo_Telephone { get; set; }
        public string UserInfo_CMND { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
